#https://learn.microsoft.com/pt-br/sql/linux/quickstart-install-connect-docker?view=sql-server-ver16&pivots=cs1-bash
version: "3"
services:
  php-ssl:
    build:
     context: ./
     dockerfile: Dockerfile
    networks:
      - frontend
      - backend
    restart: always
    ports:
     - 9080:80
     - 9443:443
    volumes:
     - ./www/:/var/www/html
     - ./php-make/upload.ini:/usr/local/etc/php/php.ini
    
    depends_on:
     - db
     - mysql
    links:
     - db
     - mysql
  
  mysql:
    container_name: mysql
    image: mysql:latest #mysql:8
    networks:
     - backend
    restart: always
    ports:
     - "3306:3306"
    environment:
     - MYSQL_ROOT_PASSWORD=Rh@b74@@2023
     - MYSQL_USER=debittouser
     - MYSQL_PASSWORD=bb0ticket002
     - MYSQL_DATABASE=dev_debitto
    volumes:
     - ./db/mysql:/var/lib/mysql
   
  db:
  #sqlserver:
    container_name: sql1
    #image: mcr.microsoft.com/mssql/server:2022-latest
    #image: mcr.microsoft.com/mssql/server:2017-latest    
    image: mcr.microsoft.com/mssql/server:2019-latest
    networks:
      - backend
    environment:
      SA_PASSWORD: "Rh@b74@@2023"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - ./db/mssql/data:/var/opt/mssql/data
      - ./db/mssql/log:/var/opt/mssql/log
      - ./db/mssql/secrets:/var/opt/mssql/secrets

  mssqltools:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - db
    volumes:
      - ./01-BaseGeografica.sql:/tmp/01-BaseGeografica.sql
      - ./02-BaseGeografica.sql:/tmp/02-BaseGeografica.sql
      - ./init-basegeografica.sh:/tmp/init-basegeografica.sh
    command: /bin/bash ./tmp/init-basegeografica.sh


networks:
   frontend:
   backend:

volumes:
   db:


